// Generated by CoffeeScript 1.9.3
"use strict";
!(function($, win, doc) {
  var $doc, $win, def, s, style, url;
  $doc = $(doc);
  $win = $(win);
  def = $.Deferred();
  s = location.hash.substring(1);
  s = s.split('##');
  if (s[0]) {
    url = s[0];
    $.ajax({
      url: url,
      crossDomain: true,
      contentType: "application/json",
      success: function(data) {
        var system;
        system = new S({});
        system.deserialize(data);
        return def.resolve(system);
      }
    }).fail(function() {
      return def.resolve(system7);
    });
  } else {
    def.resolve(system7);
  }
  style = s[1] !== '' ? Math.min(win.Themes.length - 1, parseInt(s[1])) : 1;
  return $win.load(function() {
    return $.when(def).then(function(s) {
      var ref;
      win.system = s;
      win.Theme = win.Themes[style];
      win.viewer = new Viewer({
        div: 'canvas'
      });
      win.modelview = new ModelWebView({
        div: 'canvas',
        model: system
      });
      return doc.title = ((ref = system[system.root]) != null ? ref.title : void 0) || 'Tectogram';
    });
  });
})(jQuery, window, document);

//# sourceMappingURL=app-view.js.map
