// Generated by CoffeeScript 1.9.3
"use strict";
!(function($, win, doc) {
  var $doc, $win;
  $doc = $(doc);
  $win = $(win);
  win.editor = win.viewer = null;
  win.system = win.empty_system;
  win.system.reload('autosave');
  return $win.load(function() {
    win.Theme = win.Themes[0];
    win.viewer = new Viewer({
      div: 'canvas'
    });
    win.modelview = new ModelWebViewEditable({
      div: 'canvas',
      model: system
    });
    win.editor = new Editor(system);
    win.editor.edit(system.root);
    return win.editor.load_settings();
  });
})(jQuery, window, document);

//# sourceMappingURL=app.js.map
