// Generated by CoffeeScript 1.9.3
window.i18n = function() {
  return Ember.I18n.translations = {
    measures: {
      items_per_day: ' нов./сут.',
      minutes: '&nbsp;мин.'
    },
    subs: {
      title: 'Подписки',
      add: 'Добавить подписку',
      search: {
        words: 'Тема, адрес сайта или потока'
      }
    }
  };

  /*
  		subs:
  			search:
  				words: 'Тема, адреса сайта або потоку'
  				examples: 'Приклади для пошуку:'
  				popular: 'Популярне:'
  			streams:
  				title:
  					one: 'One Follower'
  					other: 'All {{count}} Followers'
   */
};

//# sourceMappingURL=i18n.js.map
