// Generated by CoffeeScript 1.9.3
"use strict";
!(function($, win, doc) {
  var $doc, $win;
  $doc = $(doc);
  $win = $(win);
  win.ThemeGen = (function() {
    function ThemeGen(options) {
      var Levels, defaults, i, j, k, ref, ref1, s;
      defaults = {
        title: '',
        basefontsize: 7812.5,
        K: 2.5,
        xSpace: 2.5,
        xStroke: 0.02,
        xCellp: 0.16,
        xImgsize: 10,
        xWidth: 20,
        minfontsize: 5.98,
        max_imgwidth: 300,
        margin: 20,
        markersize: 5,
        fontFamily: "PT Sans",
        lineHeight: 1.25,
        rel_opacity: 0.8,
        toplevel: 1,
        slideshow: 2000,
        color: {
          text: '#000000',
          background: '#FFFFFF',
          selected: {
            stroke: '#8DBEFF',
            fill: '#FFFFE2'
          },
          stroke: '#C0C0C0',
          mask: '#C0C0C0',
          found: '#E5FF00',
          bullet: '#C0C0C0',
          emphasis: '#F08010',
          link: '#4F7FCE',
          link_hover: '#2020F0'
        }
      };
      $.extend(true, this, defaults, options);
      Levels = 10;
      this.sizes = [this.basefontsize];
      for (i = j = 0, ref = Levels; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.sizes.push(this.sizes[i] / this.K);
      }
      this.spaces = [];
      this.strokes = [];
      this.cellp = [];
      this.imgsize = [];
      this.width = [];
      for (i = k = 0, ref1 = Levels; 0 <= ref1 ? k < ref1 : k > ref1; i = 0 <= ref1 ? ++k : --k) {
        s = this.sizes[i];
        this.spaces.push(s * this.xSpace);
        this.strokes.push(s * this.xStroke);
        this.cellp.push(s * this.xCellp);
        this.imgsize.push(s * this.xImgsize);
        this.width.push(s * this.xWidth);
      }
      this.maxzoom = 1 / this.strokes[this.strokes.length - 1];
      this.minzoom = this.minfontsize / this.sizes[this.toplevel + 1];
    }

    ThemeGen.prototype.threshold = function(s) {
      var fs, i, j, len, ref;
      ref = this.sizes;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        fs = ref[i];
        if (this.minfontsize > fs * s) {
          return i;
        }
      }
      return this.sizes.length;
    };

    return ThemeGen;

  })();
  win.Themes = [];
  win.Themes.push(new ThemeGen({
    title: 'Веб',
    basefontsize: 7812.5,
    K: 2.5,
    max_imgwidth: 300,
    margin: 20,
    markersize: 5,
    fontFamily: "PT Sans",
    lineHeight: 1.25,
    slideshow: 2000,
    color: {
      selected: {
        stroke: '#8DBEFF',
        fill: '#FFFFE2'
      },
      bullet: '#C0C0C0',
      mask: '#C0C0C0',
      emphasis: '#F08010',
      link: '#4F7FCE',
      link_hover: '#2020F0'
    }
  }));
  win.Themes.push(new ThemeGen({
    title: 'Презентация',
    K: 2.5,
    fontFamily: 'Trebuchet MS',
    lineHeight: 1.33,
    color: {
      background: '#F4F4F3',
      text: '#36424E',
      bullet: '#36424E',
      stroke: '#36424E',
      mask: '#D5D8D6',
      emphasis: '#70A3EF',
      link: '#7491BC',
      link_hover: '#70A3EF',
      selected: {
        stroke: '#2D261D',
        fill: '#2D261D'
      }
    }
  }));
  win.Themes.push(new ThemeGen({
    title: 'Книга',
    K: 2.5,
    fontFamily: 'Georgia',
    lineHeight: 1.33,
    color: {
      bullet: '#A0A0A0',
      mask: '#A0A0A0',
      emphasis: '#FF3333'
    }
  }));
  win.Themes.push(new ThemeGen({
    title: 'Старая книга',
    K: 2.5,
    fontFamily: 'Georgia',
    lineHeight: 1.5,
    color: {
      background: '#FDE7B2',
      text: '#371C07',
      bullet: '#BD8E58',
      stroke: '#63481E',
      mask: '#BD8E58',
      emphasis: '#862400',
      link: '#B4794A',
      link_hover: '#FFDA73',
      selected: {
        stroke: '#2D261D',
        fill: '#2D261D'
      }
    }
  }));
  win.Themes.push(new ThemeGen({
    title: 'Печатная машинка',
    K: 2,
    fontFamily: 'courier new',
    color: {
      text: '#333333',
      emphasis: '#FF3333'
    }
  }));
  win.Themes.push(new ThemeGen({
    title: 'Рукопись 1',
    K: 2,
    xStroke: 0.085,
    markersize: 1.5,
    fontFamily: 'comic sans ms',
    lineHeight: 1.15
  }));
  win.Themes.push(new ThemeGen({
    title: 'Рукопись 2',
    K: 2.25,
    fontFamily: 'Neucha',
    lineHeight: 1.15,
    color: {
      emphasis: '#F9AF33'
    }
  }));
  return win.Theme = win.Themes[0];
})(jQuery, window, document);

//# sourceMappingURL=themes.js.map
