// Generated by CoffeeScript 1.9.3
"use strict";
var Rand;

RegExp.escape = function(text) {
  return text.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&");
};

Rand = {
  seed: 1,
  reset: function() {
    return this.seed = 1;
  },
  random: function() {
    this.seed = this.seed * 40692 % 2147483399;
    return this.seed / 2147483399;
  }
};

!(function($, win, doc) {
  var $doc, $win;
  $doc = $(doc);
  $win = $(win);
  $.key = {
    Enter: 13,
    Esc: 27,
    Down: 40,
    Up: 38,
    Left: 37,
    Right: 39,
    Tab: 9,
    Backspace: 8,
    Space: 32,
    Plus: 187,
    Minus: 189,
    Slash_cyr: 190,
    Slash: 191,
    Shift: 16,
    Ctrl: 17,
    PgUp: 33,
    PgDn: 34,
    End: 35,
    Home: 36,
    Ins: 45,
    Del: 46,
    n1: 49,
    n2: 50,
    n3: 51,
    n4: 52,
    n5: 53,
    A: 65,
    D: 68,
    F: 70,
    G: 71,
    H: 72,
    I: 73,
    J: 74,
    K: 75,
    L: 76,
    R: 82,
    S: 83,
    T: 84,
    U: 85,
    V: 86,
    W: 87,
    X: 88,
    Y: 89,
    Z: 90,
    n1_num: 97,
    n2_num: 98,
    n3_num: 99,
    n4_num: 100,
    n5_num: 101,
    n6_num: 102,
    n7_num: 103,
    n8_num: 104,
    n9_num: 105,
    Star_num: 106,
    Plus_num: 107,
    Minus_num: 109,
    Slash_num: 111
  };
  $.activeInput = function() {
    var tag;
    tag = doc.activeElement.tagName;
    return tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT";
  };
  $.clearSelection = function() {
    var sel;
    if (doc.selection && doc.selection.empty) {
      return doc.selection.empty;
    } else if (win.getSelection) {
      sel = win.getSelection();
      return sel.removeAllRanges();
    }
  };
  $.selectContents = function(id) {
    var el, range, sel;
    el = doc.getElementById(id);
    range = doc.createRange();
    range.selectNodeContents(el);
    sel = win.getSelection();
    sel.removeAllRanges();
    return sel.addRange(range);
  };
  $.selection = function() {
    var s, sel;
    s = '';
    if (win.getSelection) {
      sel = win.getSelection();
      s = sel.toString();
    }
    return s;
  };
  $.escape = function(text) {
    return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  };
  $.fn.svgRemoveClass = function(c) {
    return this.each(function(i, el) {
      var ref;
      return (ref = el.instance) != null ? ref.removeClass(c) : void 0;
    });
  };
  return $.fn.svgAddClass = function(c) {
    return this.each(function(i, el) {
      var ref;
      return (ref = el.instance) != null ? ref.addClass(c) : void 0;
    });
  };
})(jQuery, window, document);

//# sourceMappingURL=utils.js.map
