// Generated by CoffeeScript 1.9.3
"use strict";
!(function($, win, doc) {
  var $doc, $win;
  $doc = $(doc);
  $win = $(win);
  return win.Viewer = (function() {
    function Viewer(options) {
      var defaults;
      defaults = {
        div: 'canvas',
        model: {},
        smooth: false,
        svg: null
      };
      this.opt = $.extend({}, defaults, options);
      this.div = $('#' + this.opt.div);
      this.wrapper = this.div.parent();
      this.build_content();
      this.controller();
    }

    Viewer.prototype.build_content = function() {
      this.scale = 1;
      this.save_canvas_size();
      this.controls = new Ractive({
        el: 'controls',
        template: '#map-controls',
        data: {
          zoomlock: '',
          is_drawing: false,
          progress: 0
        }
      });
      this.minimap = $('#minimap .model');
      this.viewport = $('#minimap .view');
      this.wrapper.addClass('drag');
      if (this.opt.smooth) {
        this.div.addClass('smooth-transform');
      }
      return this.update_minimap();
    };

    Viewer.prototype.controller = function() {
      this.controls.on({
        'zoom-in': (function(_this) {
          return function() {
            return _this.zoom_step(true);
          };
        })(this),
        'zoom-out': (function(_this) {
          return function() {
            return _this.zoom_step(false);
          };
        })(this)
      });
      $win.on('keydown.viewer', (function(_this) {
        return function(e) {
          if (e.which === $.key.Ctrl) {
            _this.wrapper.addClass('zoom_fit');
          }
          if ($.activeInput()) {
            return true;
          } else if (e.shiftKey) {
            switch (e.which) {
              case $.key.Plus:
              case $.key.Plus_num:
                _this.zoom_step(true);
                break;
              case $.key.Minus:
              case $.key.Minus_num:
                _this.zoom_step(false);
                break;
              case $.key.Up:
                _this.pan_step(0, +1);
                break;
              case $.key.Down:
                _this.pan_step(0, -1);
                break;
              case $.key.Left:
                _this.pan_step(+1, 0);
                break;
              case $.key.Right:
                _this.pan_step(-1, 0);
                break;
              default:
                return true;
            }
            return false;
          } else {
            switch (e.which) {
              case $.key.Plus:
              case $.key.Plus_num:
                _this.zoom_step(true);
                break;
              case $.key.Minus:
              case $.key.Minus_num:
                _this.zoom_step(false);
                break;
              case $.key.n8_num:
                _this.pan_step(0, +1);
                break;
              case $.key.n2_num:
                _this.pan_step(0, -1);
                break;
              case $.key.n4_num:
                _this.pan_step(+1, 0);
                break;
              case $.key.n6_num:
                _this.pan_step(-1, 0);
                break;
              case $.key.n7_num:
                _this.pan_step(+1, +1);
                break;
              case $.key.n9_num:
                _this.pan_step(-1, +1);
                break;
              case $.key.n1_num:
                _this.pan_step(+1, -1);
                break;
              case $.key.n3_num:
                _this.pan_step(-1, -1);
                break;
              default:
                return true;
            }
            return false;
          }
          return true;
        };
      })(this));
      $win.on('keyup.viewer', (function(_this) {
        return function(e) {
          if (e.which === $.key.Ctrl) {
            return _this.wrapper.removeClass('zoom_fit');
          }
        };
      })(this));
      this.wrapper.on('mousewheel.viewer', (function(_this) {
        return function(e) {
          var factor;
          _this.fix_point(e.pageX - _this.wrapper.offset().left, e.pageY - _this.wrapper.offset().top);
          factor = e.deltaY > 0 ? _this.Settings.zoomInStep : _this.Settings.zoomOutStep;
          _this.zoom_by(factor);
          return false;
        };
      })(this));
      this.wrapper.on('mousedown.viewer', (function(_this) {
        return function(e) {
          var el;
          $.clearSelection();
          if ($.activeInput()) {
            doc.activeElement.blur();
          }
          if (e.ctrlKey) {
            el = $(e.target).closest('g')[0];
            if (el) {
              _this.zoom_fit(el.instance);
            }
            return;
          }
          _this.wrapper.addClass('dragging');
          _this.dragging = {
            x: e.clientX,
            y: e.clientY
          };
          e.preventDefault();
          return false;
        };
      })(this));
      this.wrapper.on('mousemove.viewer', (function(_this) {
        return function(e) {
          if (!_this.dragging) {
            return;
          }
          if (_this.opt.smooth) {
            _this.div.removeClass('smooth-transform');
          }
          _this.pan_by(e.clientX - _this.dragging.x, e.clientY - _this.dragging.y);
          _this.dragging.x = e.clientX;
          return _this.dragging.y = e.clientY;
        };
      })(this));
      $win.on('mouseup.viewer', (function(_this) {
        return function(e) {
          _this.wrapper.trigger('mousemove', e);
          _this.wrapper.removeClass('dragging');
          _this.dragging = null;
          if (_this.opt.smooth) {
            return _this.div.addClass('smooth-transform');
          }
        };
      })(this));
      $win.on('resize.viewer', (function(_this) {
        return function(e) {
          return _this.update_minimap();
        };
      })(this));
      if (this.opt.smooth) {
        return this.div.on('transitionend webkitTransitionEnd oTransitionEnd', (function(_this) {
          return function(e) {
            return _this.update_minimap();
          };
        })(this));
      }
    };

    Viewer.prototype.Settings = {
      zoomInStep: 1.25,
      zoomOutStep: 0.8,
      panStep: 100,
      minisize: 0.05,
      miniH: 100,
      miniW: 100
    };

    Viewer.prototype.save_canvas_size = function(w, h) {
      this.original_width = w || this.div.width();
      return this.original_height = h || this.div.height();
    };

    Viewer.prototype.update_minimap = function() {
      var dp, mh, ml, mt, mw, vh, vl, vt, vw;
      vw = this.wrapper.width() * this.Settings.minisize;
      vh = this.wrapper.height() * this.Settings.minisize;
      vl = (this.Settings.miniW - vw) / 2;
      vt = (this.Settings.miniH - vh) / 2;
      this.viewport.css({
        width: vw,
        height: vh,
        left: vl,
        top: vt
      });
      mw = this.div.width() * this.Settings.minisize;
      mh = this.div.height() * this.Settings.minisize;
      dp = this.div.position();
      ml = dp.left * this.Settings.minisize + vl;
      mt = dp.top * this.Settings.minisize + vt;
      return this.minimap.css({
        width: mw,
        height: mh,
        left: ml,
        top: mt
      });
    };

    Viewer.prototype.lock_zoom = function(param) {
      return this.controls.set('zoomlock', param);
    };

    Viewer.prototype.zoom_step = function(zoomin) {
      var factor;
      this.fix_point(this.wrapper.width() / 2, this.wrapper.height() / 2);
      factor = zoomin ? this.Settings.zoomInStep : this.Settings.zoomOutStep;
      return this.zoom_by(factor);
    };

    Viewer.prototype.zoom_by = function(factor) {
      this.scale = Math.max(Theme.minzoom, Math.min(Theme.maxzoom, this.scale * factor));
      return this.apply_scale();
    };

    Viewer.prototype.zoom = function(zoom) {
      this.scale = zoom;
      return this.apply_scale();
    };

    Viewer.prototype.scale_content = function(scale) {};

    Viewer.prototype.apply_scale = function() {
      var newh, newl, newt, neww, oldh, oldpos, oldw;
      this.lock_zoom(this.scale === Theme.minzoom ? 'min' : this.scale === Theme.maxzoom ? 'max' : '');
      oldw = this.div.width();
      oldh = this.div.height();
      oldpos = this.div.position();
      neww = this.original_width * this.scale;
      newh = this.original_height * this.scale;
      newl = this.fixed_x + (neww / oldw) * (oldpos.left - this.fixed_x);
      newt = this.fixed_y + (newh / oldh) * (oldpos.top - this.fixed_y);
      newl = Math.min(Math.max(newl, -neww), this.wrapper.width());
      newt = Math.min(Math.max(newt, -newh), this.wrapper.height());
      this.div.css({
        width: neww,
        height: newh,
        left: newl,
        top: newt
      });
      this.scale_content(this.scale);
      return this.update_minimap();
    };

    Viewer.prototype.pan_by = function(dx, dy) {
      var newl, newt, oldpos;
      oldpos = this.div.position();
      newl = oldpos.left + dx;
      newt = oldpos.top + dy;
      newl = Math.min(Math.max(newl, -this.div.width()), this.wrapper.width());
      newt = Math.min(Math.max(newt, -this.div.height()), this.wrapper.height());
      this.div.css({
        left: newl,
        top: newt
      });
      return this.update_minimap();
    };

    Viewer.prototype.pan_step = function(dx, dy) {
      return this.pan_by(dx * this.Settings.panStep, dy * this.Settings.panStep);
    };

    Viewer.prototype.fix_point = function(x, y) {
      this.fixed_x = x;
      return this.fixed_y = y;
    };

    Viewer.prototype.zoom_fit_all = function() {
      this.fix_point(0, 0);
      this.scale = Math.min(this.wrapper.height() / this.div.height(), this.wrapper.width() / this.div.width());
      return this.apply_scale();
    };

    Viewer.prototype.find_and_zoom = function(tag) {
      var el;
      el = this.div.find('g[data-model="' + tag + '"]')[0];
      if (el) {
        return this.zoom_fit(el.instance);
      }
    };

    Viewer.prototype.find_and_pan = function(tag) {
      var el;
      el = this.div.find('g[data-model="' + tag + '"]')[0];
      if (el) {
        return this.pan_to(el.instance);
      }
    };

    Viewer.prototype.pan_to = function(el) {
      var rbox;
      rbox = el.rbox();
      this.div.css({
        left: -rbox.cx + this.wrapper.width() / 2,
        top: -rbox.cy + this.wrapper.height() / 2
      });
      return this.update_minimap();
    };

    Viewer.prototype.zoom_fit = function(el) {
      var factor, rbox;
      this.fix_point(0, 0);
      rbox = el.rbox();
      factor = Math.min((this.wrapper.height() - Theme.margin) / rbox.height, (this.wrapper.width() - Theme.margin) / rbox.width);
      this.zoom_by(factor);
      rbox = el.rbox();
      this.div.css({
        left: -rbox.cx + this.wrapper.width() / 2,
        top: -rbox.cy + this.wrapper.height() / 2
      });
      return this.update_minimap();
    };

    Viewer.prototype.in_center = function() {
      var el, node, p, x, y;
      p = this.wrapper.offset();
      x = p.left + this.wrapper.width() / 2;
      y = p.top + this.wrapper.height() / 2;
      node = doc.elementFromPoint(x, y);
      el = node ? $(node).closest('g').data('model') : null;
      return el;
    };

    Viewer.prototype.is_too_big = function(tag) {
      var el, rbox;
      el = this.div.find('g[data-model="' + tag + '"]')[0];
      if (el) {
        rbox = el.instance.rbox();
        return this.wrapper.height() < rbox.height || this.wrapper.width() < rbox.width;
      } else {
        return false;
      }
    };

    Viewer.prototype.show_slide = function(el) {
      var node;
      node = this.div.find('[data-model=' + el + ']')[0];
      if (node) {
        return this.zoom_fit(node.instance);
      }
    };

    Viewer.prototype.show_story = function() {
      if (!this.model.story) {
        return;
      }
      $.each(this.model.story, (function(_this) {
        return function(i, el) {
          return $doc.queue('slides', function() {
            return setTimeout(function() {
              _this.show_slide(el);
              return $doc.dequeue('slides');
            }, Theme.slideshow);
          });
        };
      })(this));
      return $doc.dequeue('slides');
    };

    Viewer.prototype.destroy = function() {
      return this.div.empty();
    };

    return Viewer;

  })();
})(jQuery, window, document);

//# sourceMappingURL=viewer.js.map
